---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infra
  namespace: flux-system
  annotations:
    templates.fluxcd.io/tenant: "infra"
spec:
  inputs:
    # add infra below
    - component: "onepassword"
      tag: "latest"
      environment: "home"
    - component: "longhorn"
      tag: "latest"
      environment: "home"
      podSecurityLevel: "privileged"
    - component: "bjw-s"
      tag: "latest"
      environment: "home"
    - component: "tailscale"
      tag: "latest"
      environment: "home"
      # PodSecurity must be set here because the ResourceSet creates the namespace
      # before the component's Kustomization runs. ProxyGroup pods require privileged
      # access and will fail to schedule if the label is only in the component's namespace.yaml.
      podSecurityLevel: "privileged"
    - component: "tsidp"
      tag: "latest"
      environment: "home"
    - component: "grafana"
      tag: "latest"
      environment: "home"
      podSecurityLevel: "privileged"
    - component: "kubelet-serving-cert-approver"
      tag: "latest"
      environment: "home"
    - component: "metrics-server"
      tag: "latest"
      environment: "home"
    - component: "vertical-pod-autoscaler"
      tag: "latest"
      environment: "home"
    - component: "goldilocks"
      tag: "latest"
      environment: "home"

  resources:
    # Create namespace for each component
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.component >>
        labels:
          toolkit.fluxcd.io/component: << inputs.component >>
          << if get inputs "podSecurityLevel" >>pod-security.kubernetes.io/enforce: << get inputs "podSecurityLevel" >><< end >>

    # Create OCIRepository source for each component
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: OCIRepository
      metadata:
        name: infra
        namespace: << inputs.component >>
      spec:
        url: "oci://ghcr.io/bendwyer/d2-infra/<< inputs.component >>"
        ref:
          tag: << inputs.tag >>
        interval: 5m

    # Apply controllers (Helm charts, operators)
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.component >>-controllers
        namespace: << inputs.component >>
      spec:
        sourceRef:
          kind: OCIRepository
          name: infra
        path: ./controllers/<< inputs.environment >>
        prune: true
        wait: true
        interval: 10m

    # Apply configs (ClusterIssuers, Certificates, etc.)
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.component >>-configs
        namespace: << inputs.component >>
      spec:
        sourceRef:
          kind: OCIRepository
          name: infra
        path: ./configs/<< inputs.environment >>
        prune: true
        interval: 10m
        postBuild:
          substituteFrom:
            - kind: Secret
              name: << inputs.component >>
              optional: true
        dependsOn:
          - name: << inputs.component >>-controllers
          - name: onepassword-controllers
            namespace: onepassword  # Ensure operator is ready for OnePasswordItem CRDs
