---
name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "clusters/**"
      - "tenants/**"

jobs:
  test:
    uses: bendwyer/github-workflows/.github/workflows/flux-e2e.yml@main
    with:
      tenants: '["omni", "home"]'

  e2e_check:
    if: always()
    needs:
      - test
    uses: bendwyer/github-workflows/.github/workflows/github-check.yml@main
    with:
      jobs: ${{ toJSON(needs) }}
