---
name: publish-oci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "clusters/**"
      - "tenants/**"
  push:
    branches:
      - main
    paths:
      - "clusters/**"
      - "tenants/**"

jobs:
  publish:
    uses: bendwyer/github-workflows/.github/workflows/flux-publish-oci.yml@main
    with:
      oci_repo: ghcr.io/bendwyer/d2-fleet
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  check:
    if: always()
    needs:
      - publish
    uses: bendwyer/github-workflows/.github/workflows/github-check.yml@main
    with:
      jobs: ${{ toJSON(needs) }}
