---
name: publish-oci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "clusters/**"
      - "tenants/**"
  push:
    branches:
      - main
    paths:
      - "clusters/**"
      - "tenants/**"

jobs:
  publish:
    uses: bendwyer/github-workflows/.github/workflows/flux-publish-oci.yml@main
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
